config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard'
  resources :pokemons do
    resources :bookings, only: [:create, :destroy], shallow: true do
      resources :reviews, only: [:new, :create, :destroy]
    end
    get '/reviews', to: 'reviews#index', as: 'pokemon_reviews'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  before_create :calculate_total_price
  belongs_to :pokemon
  belongs_to :user
  has_one :review
  validate :correct_times
  validates :start_date, presence: true
  validates :end_date, presence: true
  def calculate_total_price
    booking_days = end_date - start_date
    self.total_price = pokemon.price_per_day * booking_days.to_i
  end

  def correct_times
    errors.add(:start_date, "Start date must be bigger then End date") if start_date > end_date
  end
end

app/models/kind.rb
class Kind < ApplicationRecord
end
  

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  include PgSearch::Model

  belongs_to :user, dependent: :destroy
  has_one_attached :photo
  has_many :bookings
  has_many :reviews, through: :bookings
  pg_search_scope :search_by_name_and_pokemon_class,
    against: [:name, :pokemon_class],
    using: {
      tsearch: { prefix: true }
    }

  validates :photo, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :pokemon_class, presence: true
  validates :price_per_day, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :pokemon, through: :booking
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pokemons, dependent: :destroy
  has_many :bookings
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
 
  def create
    @booking = Booking.new(booking_params)
    @pokemon = Pokemon.find(params[:pokemon_id])
    @booking.pokemon = @pokemon
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render "pokemons/show"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to pokemons_path(@booking.pokemon)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :pokemon_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @pokemons = Pokemon.take(6)
  end

  def dashboard
    @owned_pokemons = current_user.pokemons
    @bookings = current_user.bookings
    @date = Date.today



    @upcoming = []
    @past = []
    @bookings.each do |booking|
      if booking.start_date >= @date
        @upcoming << booking
      else
        @past << booking
        @review = Review.new
      end
    end

  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @pokemons = Pokemon.search_by_name_and_pokemon_class(params[:query])
    else
      @pokemons = Pokemon.all
    end

    @markers = @pokemons.map do |pokemon|
      {
        lat: pokemon.user.latitude,
        lng: pokemon.user.longitude
      }
    end
    @markers.reject! { |marker| marker[:lat].nil? || marker[:lng].nil? }
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @user = @pokemon.user
    @booking = Booking.new
    @markers = { lat: @user.latitude, long: @user.longitude }
    @reviews = []
    @pokemon.bookings.each do |booking|
      @reviews << booking.review
    end 

  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.user = current_user
    if @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      render 'new'
    end
  end

  def destroy
    set_pokemon.destroy
    redirect_to dashboard_path
  end

  def edit
    set_pokemon
  end

  def update
    set_pokemon
    @pokemon.update(pokemon_params)
    redirect_to dashboard_path
  end

  private

  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end

  def pokemon_params
    params.require(:pokemon).permit(:name, :description, :pokemon_class, :photo, :price_per_day)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    # @booking = Booking.find(params[:booking_id])
    @pokemon = Pokemon.find(params[:pokemon_id])
    @reviews = @pokemon.reviews
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end
  
  
  
  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    # @review.pokemon = @booking.pokemon 
    if @review.save
      redirect_to pokemon_pokemon_reviews_path(@booking.pokemon)
    else
      render 'bookings/show'
    end
  end

  def destroy
    @review = Review.find(params[:review_id])
    @review.destroy
    redirect_to booking_reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PikaPikaMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
    <% unless current_page?(root_path) %>
    <%= render 'shared/navbar' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/flashes' %>

    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-pikachu">
        <%= image_tag "Pikachu.png" %>
      </div>

      <div class="footer-copyright">
      Made with <i class="fas fa-heart"></i> by Pokélovers
      </div>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="dash-bg" class="sticky-footer">
  <div class="dash-nav">
    <div class= "dashboard-text">
    <h1 id="dashboard-heading">My Dashboard</h1>
    </div>
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">My Pokemon</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">My Pokemon Bookings</a>
      </li>

    </ul>

    <h4 class="dash-date"><%= @date.to_formatted_s(:long) %></h4>
  </div>


  <div class="dash-content-container">
    <div class="tab-content" id="pills-tabContent">

<div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <%= render "pages/dashboard_partials/my_pokemon", owned_pokemons: @owned_pokemons %>
      </div>

      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <%= render "pages/dashboard_partials/bookings", bookings: @bookings, upcoming: @upcoming, past: @past %>
      </div>


    </div>

  </div>
</div>

app/views/pages/dashboard_partials/_bookings.html.erb
<% if bookings.count >= 1 %>

<div class="dash-container">
  <% if (upcoming.count >= 1) == false  %>
  <div class="text-booking">
  <h1 class="mb-30 text-white">You don't have any upcoming Bookings.</h1>
  </div>
  <div>
    <%= link_to "Discover new Pokemons", root_path, class: "btn btn-poke"%>
    <div class="add-poke-image">
      <img src="https://freepngimg.com/thumb/pokemon/37475-6-pikachu-transparent-image.png" alt="">
    </div>
  </div>
  <% else %>
  <h3 class="dash-container-heading">My Upcoming Bookings</h3>
  <% upcoming.each do |booking|%>
  <%= link_to pokemon_path(booking.pokemon) do %>
  <% if booking.pokemon.pokemon_class == "water" %>
  <figure class="card card--water">
    <% elsif booking.pokemon.pokemon_class == "fire" %>
    <figure class="card card--fire">
      <% elsif booking.pokemon.pokemon_class == "electro" %>
      <figure class="card card--electric">
        <% elsif booking.pokemon.pokemon_class == "rock" %>
        <figure class="card card--normal">
          <% elsif booking.pokemon.pokemon_class == "poison" %>
          <figure class="card card--dark">
            <% elsif booking.pokemon.pokemon_class == "fairy" %>
            <figure class="card card--fairy">
              <% elsif booking.pokemon.pokemon_class == "grass" %>
              <figure class="card card--grass">
                <% elsif booking.pokemon.pokemon_class == "ground" %>
                <figure class="card card--normal">
                  <% elsif booking.pokemon.pokemon_class == "normal" %>
                  <figure class="card card--ice">
                    <% else booking.pokemon.pokemon_class == "bug" %>
                    <figure class="card card--psychic">
                      <% end %>

                      <div><%= link_to booking_path(booking), method: :delete, data: { confirm: "Are you sure?"} do %>
                        <div class="trash-icon"><i class="fas fa-trash"></i></div>
                        <% end %></div>

                        <div class="card__image-container">
                          <%= cl_image_tag booking.pokemon.photo.key, crop: :fill, class:"card__image" %>
                        </div>

                        <figcaption class="card__caption">
                          <h1 class="card__name"><%= link_to booking.pokemon.name, pokemon_path(booking.pokemon) %></h1>
                          <h3 class="card__type"><%= booking.pokemon.pokemon_class %></h3>
                          <div class="card__stats">
                            <p class="owner-info"><i>Owned By <%= booking.pokemon.user.first_name %></i></p>
                            <div class="owner-info"><i class="fas fa-home"></i> <%= booking.pokemon.user.address %></div>
                            <p class="booking-info"><i class="far fa-calendar-alt"></i>  <%= booking.start_date.to_formatted_s(:short) %></b> to <%= booking.end_date.to_formatted_s(:short)%></p>
                          </div>
                        </figcaption>
                      </figure>
                      <% end %>
                      <% end %>
                      <% end %>
                    <div><%= link_to "Discover New Pokemon", root_path, class: "btn btn-poke"%></div>
                    </div>

                    <% if past.count >= 1 %>
                    <div class="dash-container">
                      <h3 class="dash-container-heading">My Past Bookings</h3>
                      <% past.each do |booking|%>
                      <% if booking.pokemon.pokemon_class == "water" %>
                      <figure class="card card--water">
                        <% elsif booking.pokemon.pokemon_class == "fire" %>
                        <figure class="card card--fire">
                          <% elsif booking.pokemon.pokemon_class == "electro" %>
                          <figure class="card card--electric">
                            <% elsif booking.pokemon.pokemon_class == "rock" %>
                            <figure class="card card--normal">
                              <% elsif booking.pokemon.pokemon_class == "poison" %>
                              <figure class="card card--dark">
                                <% elsif booking.pokemon.pokemon_class == "fairy" %>
                                <figure class="card card--fairy">
                                  <% elsif booking.pokemon.pokemon_class == "grass" %>
                                  <figure class="card card--grass">
                                    <% elsif booking.pokemon.pokemon_class == "ground" %>
                                    <figure class="card card--normal">
                                      <% elsif booking.pokemon.pokemon_class == "normal" %>
                                      <figure class="card card--ice">
                                        <% else booking.pokemon.pokemon_class == "bug" %>
                                        <figure class="card card--psychic">
                                          <% end %>

                                          <div class="card__image-container">
                                            <%= cl_image_tag booking.pokemon.photo.key, crop: :fill, class:"card__image" %>
                                          </div>

                                          <figcaption class="card__caption">
                                            <h1 class="card__name"><%= link_to booking.pokemon.name, pokemon_path(booking.pokemon) %></h1>
                                            <h3 class="card__type"><%= booking.pokemon.pokemon_class %></h3>
                                            <div class="card__stats">
                                              <p class="owner-info"><i>Owned By <%= booking.pokemon.user.first_name %></i></p>

                                              <p class="booking-info"><i class="far fa-calendar-alt"></i> <b><%= booking.start_date.to_formatted_s(:short) %></b> to <%= booking.end_date.to_formatted_s(:short)%></p>


                                              <p><%= link_to "Write a review", new_booking_review_path(booking) %></p>

                                            </div>
                                          </figcaption>
                                        </figure>
                                        <% end %>


                                      </div>
                                        <% end %>


                                      <% else %>

                                      <h1 class="mb-30 text-white">You don't have any Bookings yet.</h1>
                                      <div>
                                        <%= link_to "Discover new Pokemons", root_path, class: "btn btn-poke"%>
                                        <div class="add-poke-image">
                                          <img src="https://freepngimg.com/thumb/pokemon/37475-6-pikachu-transparent-image.png" alt="">
                                        </div>
                                      </div>
                                      <% end %>
                                    </div>

app/views/pages/dashboard_partials/_dash-booked.html.erb
<div class="col-12 col-lg-6">
  <div class="my-bookings">
    <ul class="list-group">
      <% bookings.each do |booking|%>
      <li class="list-group-item">
        <p><%= booking.pokemon.name%></p>
        <p>When? <%= booking.start_date %> - <%= booking.end_date %></p>
        <p>Owner: <%= booking.user %></p>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/dashboard_partials/_dash-owned-booked.html.erb
<div class="col-12 col-lg-6">
  <div class="my-bookings">
    <ul class="list-group">
      <% @bookings.each do |booking|%>
      <li class="list-group-item">
        <p><%= booking.pokemon.name%></p>
        <p>When? <%= booking.start_date %> - <%= booking.end_date %></p>
        <p>Owner: <%= booking.user %></p>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="col-12 col-lg-6">
  <div class="my-pokemons">
    <ul class="list-group">
      <% @owned_pokemons.each do |pokemon| %>
      <li class="list-group-item pokemon-card-item">
        <div><%= cl_image_tag pokemon.photo.key, height: 100, width: 100, crop: :fill%></div>
        <div>
          <p><%= link_to pokemon.name, pokemon_path(pokemon) %></p>
          <p><i><%= pokemon.pokemon_class %></i></p>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/dashboard_partials/_dash_owned.html.erb
<div class="col-12 col-lg-6">
  <h3 class="dash-container-heading">My Pokemons</h3>
  <div class="dash-container">
    <div class="grid">
     <% @owned_pokemons.each do |pokemon| %>
      <% if pokemon.kind.name== "water" %>
        <figure class="card card--water">
      <% elsif pokemon.kind.name== "fire" %>
        <figure class="card card--fire">
      <% elsif pokemon.kind.name== "electro" %>
        <figure class="card card--electric">
      <% elsif pokemon.kind.name== "rock" %>
        <figure class="card card--normal">
      <% elsif pokemon.kind.name== "poison" %>
        <figure class="card card--dark">
      <% elsif pokemon.kind.name== "fairy" %>
        <figure class="card card--fairy">
      <% elsif pokemon.kind.name== "grass" %>
        <figure class="card card--grass">
      <% elsif pokemon.kind.name== "ground" %>
        <figure class="card card--normal">
      <% elsif pokemon.kind.name== "normal" %>
        <figure class="card card--ice">
      <% else pokemon.kind.name== "bug" %>
        <figure class="card card--psychic">
      <% end %>

    <div class="edit-btn"><%= link_to "Edit", edit_pokemon_path(pokemon), class: "btn btn-light"%></div>
    <div><%= link_to pokemon_path(pokemon), method: :delete, data: { confirm: "Are you sure?"} do %>
      <div class="trash-icon"><i class="fas fa-trash"></i></div>
    <% end %>
    </div>

     <div class="card__image-container">
      <%= cl_image_tag pokemon.photo.key, crop: :fill, class:"card__image" %>
    </div>

    <figcaption class="card__caption">
      <h1 class="card__name"><%= link_to pokemon.name, pokemon_path(pokemon) %></h1>
      <h3 class="card__type"><%= pokemon.kind.name%></h3>
    </figcaption>
  </figure>
  <% end %>
</div>
<div><%= link_to "Add New Pokemon", new_pokemon_path, class: "btn btn-primary"%></div>
</div>
</div>


<div class="col-12 col-lg-6">
  <h3 class="dash-container-heading">My Pokemon Bookings</h3>
  <div class="dash-container" id="discover-new" style= "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://freepngimg.com/thumb/pokemon/37475-6-pikachu-transparent-image.png)">
    <div id="discover-new-content">
      <h1>You Can Find New Pokemons Anywhere</h1>
      <div><%= link_to "Discover", root_path, class: "btn btn-primary"%></div>
    </div>
  </div>
</div>

app/views/pages/dashboard_partials/_my_pokemon.html.erb
<% if owned_pokemons.count >= 1 %>
    <div class="grid">
     <% owned_pokemons.each do |pokemon| %>
      <% if pokemon.pokemon_class == "water" %>
        <figure class="card card--water">
      <% elsif pokemon.pokemon_class == "fire" %>
        <figure class="card card--fire">
      <% elsif pokemon.pokemon_class == "electro" %>
        <figure class="card card--electric">
      <% elsif pokemon.pokemon_class == "rock" %>
        <figure class="card card--normal">
      <% elsif pokemon.pokemon_class == "poison" %>
        <figure class="card card--dark">
      <% elsif pokemon.pokemon_class == "fairy" %>
        <figure class="card card--fairy">
      <% elsif pokemon.pokemon_class == "grass" %>
        <figure class="card card--grass">
      <% elsif pokemon.pokemon_class == "ground" %>
        <figure class="card card--normal">
      <% elsif pokemon.pokemon_class == "normal" %>
        <figure class="card card--ice">
      <% else pokemon.pokemon_class == "bug" %>
        <figure class="card card--psychic">
      <% end %>

    <div class="edit-btn"><%= link_to "Edit", edit_pokemon_path(pokemon), class: "btn btn-light"%></div>
    <div><%= link_to pokemon_path(pokemon), method: :delete, data: { confirm: "Are you sure?"} do %>
      <div class="trash-icon"><i class="fas fa-trash"></i></div>
    <% end %>
    </div>

     <div class="card__image-container">
      <%= cl_image_tag pokemon.photo.key, crop: :fill, class:"card__image" %>
    </div>

    <figcaption class="card__caption">
      <h1 class="card__name"><%= link_to pokemon.name, pokemon_path(pokemon) %></h1>
      <h3 class="card__type"><%= pokemon.pokemon_class %></h3>
    </figcaption>
  </figure>
    <% end %>
    <div><%= link_to "Add New Pokemon", new_pokemon_path, class: "btn btn-poke"%></div>
    </div>

<% else %>

<div class="">
  <h1 class="mb-30 text-white">You haven't uploaded any Pokemons yet.</h1>
  <div>
      <%= link_to "Add New Pokemon", new_pokemon_path, class: "btn btn-poke"%>
      <div class="add-poke-image">
        <img src="https://freepngimg.com/thumb/pokemon/37475-6-pikachu-transparent-image.png" alt="">
      </div>
</div>
<% end %>

app/views/pages/home.html.erb
<header>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="https://assets.pokemon.com//assets/cms2/img/misc/virtual-backgrounds/sword-shield/pokemon-in-the-wild.mp4" type="video/mp4">
  </video>

  <%= render 'shared/navbarhome' %>

  <div class="container h-100 mx-auto">

    <div class="d-flex h-100 text-center align-items-center">

      <div class="w-100 text-white mt-5">

        <h1 class="display-3">Gotta catch 'em all!</h1>

          <%= form_tag pokemons_path, method: :get, class: "search-bar" do %>
            <div class="wrapper d-flex">
            <%= text_field_tag :query,
              params[:query],
              placeholder: "Find a pokemon"
            %>
            <%= submit_tag "Search", class: "button-home" %>
            </div>

          <% end %>

          <div class="button-group">
            <a href="http://localhost:3000/pokemons?query=grass&commit=Search" class="button-search-grass mr-2">Grass</a>
            <a href="http://localhost:3000/pokemons?query=fire&commit=Search" class="button-search-fire mr-2">Fire</a>
            <a href="http://localhost:3000/pokemons?query=electro&commit=Search" class="button-search-electric mr-2">Electro</a>
            <a href="http://localhost:3000/pokemons?query=psychic&commit=Search" class="button-search-psychic mr-2">Psychic</a>
            <a href="http://localhost:3000/pokemons?query=water&commit=Search" class="button-search-water mr-2">Water</a>
          </div>
      </div>
    </div>
  </div>
</header>

<div class="background-color">
    <div class="cards">
    <% @pokemons.each do |pokemon| %>
    <%= link_to pokemon_path(pokemon), class: "cards-text" do %>
     <% if pokemon.pokemon_class == "water" %>
        <figure class="card card--water">
      <% elsif pokemon.pokemon_class == "fire" %>
        <figure class="card card--fire">
      <% elsif pokemon.pokemon_class == "electro" %>
        <figure class="card card--electric">
      <% elsif pokemon.pokemon_class == "rock" %>
        <figure class="card card--normal">
      <% elsif pokemon.pokemon_class == "poison" %>
        <figure class="card card--dark">
      <% elsif pokemon.pokemon_class == "fairy" %>
        <figure class="card card--fairy">
      <% elsif pokemon.pokemon_class == "grass" %>
        <figure class="card card--grass">
      <% elsif pokemon.pokemon_class == "ground" %>
        <figure class="card card--normal">
      <% elsif pokemon.pokemon_class == "normal" %>
        <figure class="card card--ice">
      <% else pokemon.pokemon_class == "bug" %>
        <figure class="card card--psychic">
      <% end %>

      <div class="card__image-container">
        <%= cl_image_tag pokemon.photo.key, crop: :fill, class:"card__image" %>
      </div>
      <figcaption class="card__caption">

        <h1 class="card__name"><%= pokemon.name %></h1>

        <h3 class="card__type">
         <%= pokemon.pokemon_class %>
        </h3>

        <table class="card__stats">
          <tbody>
          <tr>
            <th class="description"><%= pokemon.description%></th>
          </tr>
        </tbody></table>

        <div class="card__abilities">
          <h4 class="card__ability">
            <span class="card__label">Ability</span>
            <%= Faker::Games::Pokemon.move %>
          </h4>
          <h4 class="card__ability">
            <span class="card__label">Price</span>
            € <%= pokemon.price_per_day %>
          </h4>
        </div>
      </figcaption>
    </figure>
    <% end %>
    <% end %>
</div>

app/views/pokemons/edit.hmtl.erb
<h1>Edit Pokemon</h1>

<%= simple_form_for @pokemon do |f| %>
  <%= f.input :name %>
  <%= f.input :pokemon_class %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.submit %>
<% end %>

app/views/pokemons/edit.html.erb
<div class="background-new">
<div class="margin-zero">
  <h2 class="text-white mb-30">Edit <%= @pokemon.name %></h2>
  <%= simple_form_for @pokemon do |f| %>
  <figure class="card card--normal">
    <div class="card__image-container">
      <%= f.input :photo, as: :file, label: false %>
    </div>

    <figcaption class="card__caption">
      <h1 class="card__name">
        <%= f.input :name, label: false, :input_html => { :style=> "width: 100px; border-radius: 5px"}, :placeholder => "Edit" %>
      </h1>

      <h3 class="card__type">
        <%= f.input :pokemon_class, label: false, :input_html => { :style=> "width: 100px; border-radius: 5px"}, :placeholder => "Edit" %>
      </h3>

      <table class="card__stats">
        <tbody><tr>
          <%= f.input :description, label: false, :placeholder => "Edit", :input_html => { :style=> "width: 270px; border-radius: 5px"} %>
      </tbody></table>

      <div class="card__abilities">
        <h4 class="card__ability">
          <span class="card__label"></span>
          <%= f.submit '', class: 'btn-pokemon-new'%>
        </h4>
        <h4 class="card__ability">
          <span class="card__label">
          </span>
          <%= f.input :price_per_day, label: false, :placeholder => "Edit", :input_html => { :style=> "width: 120px; border-radius: 5px"}%>
        </h4>
      </div>
    </figcaption>
  </figure>
  <% end %>
</div>
</div>

app/views/pokemons/new.html.erb
<div class="background-new">
<%= simple_form_for @pokemon do |f| %>
<figure class="card card--water">
  <div class="card__image-container">
    <%= f.input :photo, as: :file, label: false %>
  </div>

  <figcaption class="card__caption">
    <h1 class="card__name">
      <%= f.input :name, label: false, :input_html => { :style=> "width: 80px; border-radius: 5px"}, :placeholder => "Add Name" %>
    </h1>

    <h3 class="card__type">
      <%= f.input :pokemon_class, label: false, :input_html => { :style=> "width: 80px; border-radius: 5px"}, :placeholder => "Add Type" %>
    </h3>

    <table class="card__stats">
      <tbody><tr>
        <%= f.input :description, label: false, :placeholder => "Add Description", :input_html => { :style=> "width: 270px; border-radius: 5px"} %>
    </tbody></table>

    <div class="card__abilities">
      <h4 class="card__ability">
        <span class="card__label"></span>
        <%= f.submit 'Create', class: 'btn-pokemon-new'%>
      </h4>
      <h4 class="card__ability">
        <span class="card__label">
        </span>
        <%= f.input :price_per_day, label: false, :placeholder => "Add Price", :input_html => { :style=> "width: 120px; border-radius: 5px"}%>
      </h4>
    </div>
  </figcaption>
</figure>
<% end %>
</div>

app/views/reviews/index.html.erb
<div class="sticky-footer">
  <h1> Reviews for <%= @pokemon.name %></h1>

  <ul>
    <% @reviews.each do |review| %>
      <li><%= review.booking.user.first_name %> <%= review.booking.user.last_name %></li>
      <li><%= review.content %></li>
    <% end %>
  </ul>
</div>

app/views/reviews/new.html.erb
<div class="background-log">
  <div class="card-log-in">
    <h2>Write a review!</h2>

    <%= simple_form_for [@booking, @review] do |f| %>
      <div class="form-inputs mt-3">
        <%= f.input :content %>
      </div>

      <div class="form-actions">
        <%= f.submit "Submit your review" %>
      </div>
    <% end %>

    <%= image_tag "Pikachu.png", class: "pikachu" %>
  </div>
</div>